#ifndef COLIB_UI_CONSTANTS_HPP
#define COLIB_UI_CONSTANTS_HPP

#include <CoLib/UI/Export.hpp>

namespace co
{

    const extern s8t COLIB_UI_API NODE_ALREADY_ATTACHED_STRING;
    const extern s8t COLIB_UI_API NODE_ALREADY_DETACHED_STRING;
    const extern s8t COLIB_UI_API OWN_ANCESTOR_NODE_STRING;
    const extern s8t COLIB_UI_API PARENT_NODES_NOT_SUPPORTED_STRING;
    const extern s8t COLIB_UI_API CHILD_NODES_NOT_SUPPORTED_STRING;

}

#endif // COLIB_UI_CONSTANTS_HPP