#ifndef COLIB_GRAPHICS_EXPORT_HPP
#define COLIB_GRAPHICS_EXPORT_HPP

#include <CoLib/Config.hpp>

#ifdef COLIB_GRAPHICS_EXPORTS
#define COLIB_GRAPHICS_API COLIB_API_EXPORT
#else
#define COLIB_GRAPHICS_API COLIB_API_IMPORT
#endif

#endif // COLIB_GRAPHICS_EXPORT_HPP