#ifndef COLIB_SYSTEM_CONSTANTS_HPP
#define COLIB_SYSTEM_CONSTANTS_HPP

#include <CoLib/System/Export.hpp>

namespace co
{

    const extern COLIB_SYSTEM_API s8t LIBRARY_VERSION_STRING;
    const extern COLIB_SYSTEM_API s8t UNKNOWN_EXCEPTION_STRING;
    const extern COLIB_SYSTEM_API s8t NOT_IMPLEMENTED_EXCEPTION_STRING;
    const extern COLIB_SYSTEM_API s8t INVALID_OPERATION_EXCEPTION_STRING;

}

#endif // COLIB_SYSTEM_CONSTANTS_HPP