#ifndef COLIB_SYSTEM_CONSTANTS_HPP
#define COLIB_SYSTEM_CONSTANTS_HPP

#include <CoLib/System/Export.hpp>

namespace co
{

    const extern s8t COLIB_SYSTEM_API LIBRARY_VERSION;

    const extern s8t COLIB_SYSTEM_API UNKNOWN_EXCEPTION_MESSAGE;
    const extern s8t COLIB_SYSTEM_API NOT_IMPLEMENTED_EXCEPTION_MESSAGE;
    const extern s8t COLIB_SYSTEM_API INVALID_VALUE_EXCEPTION_MESSAGE;
    const extern s8t COLIB_SYSTEM_API INVALID_OPERATION_EXCEPTION_MESSAGE;
    const extern s8t COLIB_SYSTEM_API INVALID_STATE_EXCEPTION_MESSAGE;

}

#endif // COLIB_SYSTEM_CONSTANTS_HPP