#ifndef COLIB_SYSTEM_CONSTANTS_HPP
#define COLIB_SYSTEM_CONSTANTS_HPP

#include <CoLib/System/Export.hpp>

namespace co
{

    const extern s8t COLIB_SYSTEM_API LIBRARY_VERSION_STRING;
    const extern s8t COLIB_SYSTEM_API UNKNOWN_EXCEPTION_STRING;
    const extern s8t COLIB_SYSTEM_API NOT_IMPLEMENTED_EXCEPTION_STRING;
    const extern s8t COLIB_SYSTEM_API INVALID_OPERATION_EXCEPTION_STRING;

    const extern s8t COLIB_SYSTEM_API JOB_STILL_ATTACHED_STRING;
    const extern s8t COLIB_SYSTEM_API JOB_ALREADY_ATTACHED_STRING;
    const extern s8t COLIB_SYSTEM_API JOB_ALREADY_DETACHED_STRING;

    const extern s8t COLIB_SYSTEM_API EMPTY_TASK_STRING;

}

#endif // COLIB_SYSTEM_CONSTANTS_HPP