#ifndef COLIB_DESIGN_EXPORT_HPP
#define COLIB_DESIGN_EXPORT_HPP

#include <CoLib/Config.hpp>

#ifdef COLIB_DESIGN_EXPORTS
#define COLIB_DESIGN_API COLIB_API_EXPORT
#else
#define COLIB_DESIGN_API COLIB_API_IMPORT
#endif

#endif // COLIB_DESIGN_EXPORT_HPP